name: benchmark

on:
  push:
    branches: "main"
jobs:
  runbenchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: take benchmarks
      run: |
        mkdir -p document
        ./benchmark/gendoc.sh ${{ github.sha }} | tee document/Benchmarks.md
    - name: upload to wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: "document"
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
