name: C

on:
  pull_request:
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run tests
      run: |
        make c
        ./planck < bootstrap.fs runtests.fs
