name: i386-linux-handwritten

on:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: run tests
          run: |
              make
              ./planck < bootstrap.fs runtests.fs

