name: python

on:
  push:
jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: run tests
      run: |
        make python
        ./planck < bootstrap.fs runtests.fs
